language: python

os:
  - windows

python: "3.6"

jobs:
  include:
  - stage: pyinstaller
    script: pip install pyinstaller
    script: pyinstaller --console --clean --onefile --name "KCD-Save-Backuper" kdcsbak.py 
  - stage: GitHub Release
    script: echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      overwrite: true
      file: "dist/KCD-Save-Backuper.exe"
      on:
        tags: true